### ISSUE TITLE
Wrong trace position? 

### ISSUE THREAD

**Issue by aspertime** [TOILmodular/EurorackWaveFolder#1]
I have built the Wavefolder module using the Gerbers from this depository, and there's no sound coming out.
I started troubleshooting and found that the trace going from the input to R1 is connected to the 'switch', and not to the 'tip', and this might be the reason why no signal is passing over to R1.
I don't know if it's by mistake or not, but if it is by mistake then there might be other issues further down the signal path.
![100k](https://github.com/user-attachments/assets/88f98847-e3b4-46ea-b35d-7b373e889e69)

**Comment by TOILmodular** [comment]
You are right. The issue is not only with the input jack, but also with the output jack. I did not realize because I did not use the Thonk version for my build. I updated the Gerber file with the corrected version. If you still want to use your PCB, you can just use a piece of wire (e.g. a resistor leg) and connect the tip of the input jack with the right side 100 K resistor and the tip of the left output jack with the left side 470R resistor. You do not even have to cut the existing connections, since they will not be used, when plugging in patch cables. Sorry for the mistake and thanks for letting me know.

**Comment by aspertime** [comment]
Thanks for clarifying and for offering a workaround.
You're doing an awesome job with your designs and I already have a few more on queue.
I appreciate your efforts, keep it coming.
